### ISSUE TITLE
Redis.AUTH: ERR Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by uniteweiwei** [druidcaesa/monkey-admin#1]
启动服务的时候,说Redis服务器没有设置密码，但客户端向其发送了AUTH（authentication，身份验证）请求携带着密码，导致报错

**Comment by uniteweiwei** [comment]
![image](https://user-images.githubusercontent.com/19373139/131943707-3c116c50-e916-4151-988b-2856a9e5a8a7.png)

**Comment by druidcaesa** [comment]
该问题已修复，感谢提出的意见，因为redis一般都未设置上密码，所以没有考虑到没有密码的情况。AUTH主要是用于redis链接有密码时进行权限认证使用，这里已经在链接时进行了判断，当密码存在时进行密码认证

**Comment by uniteweiwei** [comment]
嗯嗯,好的,谢谢
